Smoovio\Bundle\CoreBundle\Entity\Person:
  type: mappedSuperclass
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
    biography:
      type: text
      nullable: true
    homepage:
      type: string
      nullable: true
    birthday:
      type: datetime
      nullable: true
    deathday:
      type: datetime
      nullable: true
