Smoovio\Bundle\CoreBundle\Entity\User:
  type: entity
  table: user
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    username:
      type: string
    password:
      type: string
    email:
      type: string
    salt:
      type: string
